spring:
  datasource:
    url: jdbc:postgresql://bubble.db.elephantsql.com:5432/kgocbwrk
    username: kgocbwrk
    password: ZFfrExlDrxSeEIHIlCP-4EfZonV5nB93
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
